apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app-deployment
  labels:
    app: nextjs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - name: nextjs-app-container
        image: PLACEHOLDER_IMAGE
        resources:
          requests:
            cpu: "0.1"           
            memory: "512Mi"
          limits:
            cpu: "0.1"
            memory: "512Mi"
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: databasehost
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          value: databaseuser
        - name: DATABASE_PASSWORD
          value: databasepassword
        - name: DATABASE_NAME
          value: databasename
  
