name: Deploy to Kubernetes on EC2

on:
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: "Tag for the Docker image"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_REPOSITORY: ${{ vars.DOCKER_HUB_USERNAME }}/${{ vars.DOCKER_HUB_REPOSITORY }}
      IMAGE_NAME: ${{ vars.DOCKER_HUB_REPOSITORY }}
      IMAGE_TAG: ${{ github.event.inputs.IMAGE_TAG }}
      KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Configure kubeconfig for the cluster
        run: |
          mkdir -p ~/.kube
          echo ${{ env.KUBECONFIG_CONTENT }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Verify kubectl connection
        run: |
          kubectl config view
          kubectl cluster-info
          kubectl get nodes

      - name: Prepare deployment file
        run: |
          # Print environment variables
          echo "DOCKER_HUB_REPOSITORY: ${{ env.DOCKER_HUB_REPOSITORY }}"
          echo "IMAGE_TAG: ${{ env.IMAGE_TAG }}"
          
          # Print the deployment file before replacement
          echo "Before replacement:"
          cat deployment.yml
          
          # Do the replacement
          sed -i "s|image: PLACEHOLDER_IMAGE|image: ${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.IMAGE_TAG }}|" deployment.yml
          
          # Print the deployment file after replacement
          echo "After replacement:"
          cat deployment.yml
          
          # Verify the exact image string that will be used
          echo "Expected image string: ${{ env.DOCKER_HUB_REPOSITORY }}:${{ env.IMAGE_TAG }}"
          grep "image:" deployment.yml

      # Add this new step to actually apply the deployment
      - name: Apply deployment
        run: |
          kubectl apply -f deployment.yml
          kubectl get deployments
          kubectl get pods